// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsActivityRecognitionPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsActivityRecognitionPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsActivityRecognitionPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashActivityRecognitionPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashActivityRecognitionPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashActivityRecognitionPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Represents an activity type detected by the device
enum ActivityTypeData: Int {
  case inVehicle = 0
  case onBicycle = 1
  case onFoot = 2
  case running = 3
  case still = 4
  case tilting = 5
  case unknown = 6
  case walking = 7
}

/// Represents an activity event with type, confidence, and timestamp
///
/// Generated class from Pigeon that represents data sent in messages.
struct ActivityEventData: Hashable {
  /// The type of activity detected
  var type: ActivityTypeData
  /// The confidence level (0-100) of the detection
  var confidence: Int64
  /// The timestamp when the activity was detected (milliseconds since epoch)
  var timestamp: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActivityEventData? {
    let type = pigeonVar_list[0] as! ActivityTypeData
    let confidence = pigeonVar_list[1] as! Int64
    let timestamp = pigeonVar_list[2] as! Int64

    return ActivityEventData(
      type: type,
      confidence: confidence,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      confidence,
      timestamp,
    ]
  }
  static func == (lhs: ActivityEventData, rhs: ActivityEventData) -> Bool {
    return deepEqualsActivityRecognitionPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashActivityRecognitionPigeon(value: toList(), hasher: &hasher)
  }
}

/// Configuration for starting activity recognition
///
/// Generated class from Pigeon that represents data sent in messages.
struct ActivityRecognitionConfig: Hashable {
  /// Whether to run a foreground service (Android only)
  var runForegroundService: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActivityRecognitionConfig? {
    let runForegroundService = pigeonVar_list[0] as! Bool

    return ActivityRecognitionConfig(
      runForegroundService: runForegroundService
    )
  }
  func toList() -> [Any?] {
    return [
      runForegroundService
    ]
  }
  static func == (lhs: ActivityRecognitionConfig, rhs: ActivityRecognitionConfig) -> Bool {
    return deepEqualsActivityRecognitionPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashActivityRecognitionPigeon(value: toList(), hasher: &hasher)
  }
}

private class ActivityRecognitionPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ActivityTypeData(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ActivityEventData.fromList(self.readValue() as! [Any?])
    case 131:
      return ActivityRecognitionConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ActivityRecognitionPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ActivityTypeData {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ActivityEventData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ActivityRecognitionConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ActivityRecognitionPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ActivityRecognitionPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ActivityRecognitionPigeonPigeonCodecWriter(data: data)
  }
}

class ActivityRecognitionPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ActivityRecognitionPigeonPigeonCodec(readerWriter: ActivityRecognitionPigeonPigeonCodecReaderWriter())
}

/// Host API - Methods implemented on the native side (Android/iOS) and called from Flutter
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ActivityRecognitionHostApi {
  /// Starts activity recognition with the given configuration
  /// Returns null on success, throws FlutterError on failure
  func startActivityUpdates(config: ActivityRecognitionConfig) throws
  /// Stops activity recognition
  func stopActivityUpdates() throws
  /// Checks if activity recognition is available on the device
  func isActivityRecognitionAvailable() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ActivityRecognitionHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ActivityRecognitionPigeonPigeonCodec.shared }
  /// Sets up an instance of `ActivityRecognitionHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ActivityRecognitionHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts activity recognition with the given configuration
    /// Returns null on success, throws FlutterError on failure
    let startActivityUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.startActivityUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startActivityUpdatesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ActivityRecognitionConfig
        do {
          try api.startActivityUpdates(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startActivityUpdatesChannel.setMessageHandler(nil)
    }
    /// Stops activity recognition
    let stopActivityUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.stopActivityUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopActivityUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.stopActivityUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopActivityUpdatesChannel.setMessageHandler(nil)
    }
    /// Checks if activity recognition is available on the device
    let isActivityRecognitionAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.isActivityRecognitionAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isActivityRecognitionAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isActivityRecognitionAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isActivityRecognitionAvailableChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API - Methods implemented in Flutter and called from native code
/// Used to send activity events from native to Flutter
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ActivityRecognitionFlutterApiProtocol {
  /// Called when a new activity is detected on the native side
  func onActivityUpdate(event eventArg: ActivityEventData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ActivityRecognitionFlutterApi: ActivityRecognitionFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ActivityRecognitionPigeonPigeonCodec {
    return ActivityRecognitionPigeonPigeonCodec.shared
  }
  /// Called when a new activity is detected on the native side
  func onActivityUpdate(event eventArg: ActivityEventData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionFlutterApi.onActivityUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
