// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Represents an activity type detected by the device
enum ActivityTypeData {
  inVehicle,
  onBicycle,
  onFoot,
  running,
  still,
  tilting,
  unknown,
  walking,
}

/// Represents an activity event with type, confidence, and timestamp
class ActivityEventData {
  ActivityEventData({
    required this.type,
    required this.confidence,
    required this.timestamp,
  });

  /// The type of activity detected
  ActivityTypeData type;

  /// The confidence level (0-100) of the detection
  int confidence;

  /// The timestamp when the activity was detected (milliseconds since epoch)
  int timestamp;

  List<Object?> _toList() {
    return <Object?>[
      type,
      confidence,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static ActivityEventData decode(Object result) {
    result as List<Object?>;
    return ActivityEventData(
      type: result[0]! as ActivityTypeData,
      confidence: result[1]! as int,
      timestamp: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ActivityEventData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for starting activity recognition
class ActivityRecognitionConfig {
  ActivityRecognitionConfig({
    required this.runForegroundService,
  });

  /// Whether to run a foreground service (Android only)
  bool runForegroundService;

  List<Object?> _toList() {
    return <Object?>[
      runForegroundService,
    ];
  }

  Object encode() {
    return _toList();  }

  static ActivityRecognitionConfig decode(Object result) {
    result as List<Object?>;
    return ActivityRecognitionConfig(
      runForegroundService: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ActivityRecognitionConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ActivityTypeData) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ActivityEventData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ActivityRecognitionConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ActivityTypeData.values[value];
      case 130: 
        return ActivityEventData.decode(readValue(buffer)!);
      case 131: 
        return ActivityRecognitionConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API - Methods implemented on the native side (Android/iOS) and called from Flutter
class ActivityRecognitionHostApi {
  /// Constructor for [ActivityRecognitionHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ActivityRecognitionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts activity recognition with the given configuration
  /// Returns null on success, throws FlutterError on failure
  Future<void> startActivityUpdates(ActivityRecognitionConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.startActivityUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stops activity recognition
  Future<void> stopActivityUpdates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.stopActivityUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Checks if activity recognition is available on the device
  Future<bool> isActivityRecognitionAvailable() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.isActivityRecognitionAvailable$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// Flutter API - Methods implemented in Flutter and called from native code
/// Used to send activity events from native to Flutter
abstract class ActivityRecognitionFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when a new activity is detected on the native side
  void onActivityUpdate(ActivityEventData event);

  static void setUp(ActivityRecognitionFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionFlutterApi.onActivityUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionFlutterApi.onActivityUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ActivityEventData? arg_event = (args[0] as ActivityEventData?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionFlutterApi.onActivityUpdate was null, expected non-null ActivityEventData.');
          try {
            api.onActivityUpdate(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
