// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dk.cachet.activity_recognition_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ActivityRecognitionPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Represents an activity type detected by the device */
enum class ActivityTypeData(val raw: Int) {
  IN_VEHICLE(0),
  ON_BICYCLE(1),
  ON_FOOT(2),
  RUNNING(3),
  STILL(4),
  TILTING(5),
  UNKNOWN(6),
  WALKING(7);

  companion object {
    fun ofRaw(raw: Int): ActivityTypeData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents an activity event with type, confidence, and timestamp
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ActivityEventData (
  /** The type of activity detected */
  val type: ActivityTypeData,
  /** The confidence level (0-100) of the detection */
  val confidence: Long,
  /** The timestamp when the activity was detected (milliseconds since epoch) */
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ActivityEventData {
      val type = pigeonVar_list[0] as ActivityTypeData
      val confidence = pigeonVar_list[1] as Long
      val timestamp = pigeonVar_list[2] as Long
      return ActivityEventData(type, confidence, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      confidence,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ActivityEventData) {
      return false
    }
    if (this === other) {
      return true
    }
    return ActivityRecognitionPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for starting activity recognition
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ActivityRecognitionConfig (
  /** Whether to run a foreground service (Android only) */
  val runForegroundService: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ActivityRecognitionConfig {
      val runForegroundService = pigeonVar_list[0] as Boolean
      return ActivityRecognitionConfig(runForegroundService)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runForegroundService,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ActivityRecognitionConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return ActivityRecognitionPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ActivityRecognitionPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ActivityTypeData.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ActivityEventData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ActivityRecognitionConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ActivityTypeData -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ActivityEventData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ActivityRecognitionConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host API - Methods implemented on the native side (Android/iOS) and called from Flutter
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ActivityRecognitionHostApi {
  /**
   * Starts activity recognition with the given configuration
   * Returns null on success, throws FlutterError on failure
   */
  fun startActivityUpdates(config: ActivityRecognitionConfig)
  /** Stops activity recognition */
  fun stopActivityUpdates()
  /** Checks if activity recognition is available on the device */
  fun isActivityRecognitionAvailable(): Boolean

  companion object {
    /** The codec used by ActivityRecognitionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ActivityRecognitionPigeonPigeonCodec()
    }
    /** Sets up an instance of `ActivityRecognitionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ActivityRecognitionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.startActivityUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ActivityRecognitionConfig
            val wrapped: List<Any?> = try {
              api.startActivityUpdates(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              ActivityRecognitionPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.stopActivityUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopActivityUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              ActivityRecognitionPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.isActivityRecognitionAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isActivityRecognitionAvailable())
            } catch (exception: Throwable) {
              ActivityRecognitionPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API - Methods implemented in Flutter and called from native code
 * Used to send activity events from native to Flutter
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ActivityRecognitionFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ActivityRecognitionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ActivityRecognitionPigeonPigeonCodec()
    }
  }
  /** Called when a new activity is detected on the native side */
  fun onActivityUpdate(eventArg: ActivityEventData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionFlutterApi.onActivityUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ActivityRecognitionPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
